name: flutter_app
description: A Flutter application for the final research project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  cupertino_icons: ^1.0.2
  provider: ^6.1.5+1

<<<<<<< HEAD
  # Camera / Image Picker
  image_picker: ^0.8.7+6
  cross_file: ^0.3.4+2

=======
>>>>>>> 4cbdab79bc9f34dbebb7b4401209701ea2169c3f
  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12

  # Location / GPS
  geolocator: ^10.1.0

<<<<<<< HEAD
  # HTTP requests
  http: ^1.6.0

  # Logging
  logger: ^2.4.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_plus: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
=======
dev_dependencies:
  flutter_test:
    sdk: flutter

>>>>>>> 4cbdab79bc9f34dbebb7b4401209701ea2169c3f
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
