name: flutter_app
description: A Flutter application for the final research project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  cupertino_icons: ^1.0.2
  provider: ^6.1.5+1

  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12

  # Location / GPS
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
